news/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
                       url(r'^$', 'news.views.index', name='news'),
                       # url(r'^xindex/', 'news.views.xindex'),
                       url(r'^page/(?P<page>\d+)/', 'news.views.index'),
                       # url(r'^xpage/(?P<page>\d+)/', 'news.views.xindex'),
                       url(r'^admin/addnews/', 'news.views.add_news'),
                       url(r'^admin/editnews/', 'news.views.edit_news'),
                       url(r'^admin/addcategory/', 'news.views.add_category'),
                       url(r'^admin/remcategory/', 'news.views.remcat'),
                       url(r'^admin/remnews/', 'news.views.remnews'),
                       url(r'^admin/remtags/', 'news.views.remtags'),
                       url(r'^admin/', 'news.views.admin'),
                       # url(r'^xadmin/', 'news.views.xadmin'),
                       url(r'^addcomment/', 'news.views.addcomment'),
                       url(r'^sp/(?P<id>\d+)/', 'news.views.sp'),
                       # url(r'^xsp/(?P<id>\d+)/', 'news.views.xsp'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from sitemap import Newss, Statics, StaticIndex

sitemaps = {'Index': StaticIndex,
            'Static': Statics,
            'News': Newss}
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'gk.views.index', name='index'),
                       url(r'^el/', 'gk.views.el', name='about'),
                       url(r'^about/', 'gk.views.about', name='about'),
                       url(r'^contacts/', 'gk.views.contacts', name='contacts'),
                       url(r'^reg/', 'gk.views.reg', name='reg'),
                       url(r'^fpass/', 'gk.views.fpass'),
                       url(r'^snpass/(?P<key>\w+)/', 'gk.views.snpass'),
                       url(r'^login/', 'gk.views.loginv'),
                       url(r'^logout/', 'gk.views.logoutv'),
                       url(r'^emailv/(?P<key>\w+)/', 'gk.views.email_verification'),
                       url(r'^ads/', 'gk.views.ads', name='ads'),
                       url(r'^allcam/', 'gk.views.allcam'),
                       url(r'^elallcam/', 'gk.views.allcam'),
                       url(r'^lastcameras/', 'gk.views.lastcameras'),
                       url(r'^topcamera/', 'gk.views.topcamera'),
                       url(r'^getcity/', 'gk.views.getcity'),
                       url(r'^topcameras/(?P<step>\d+)/', 'gk.views.topcameras'),
                       url(r'^get_camera-(?P<camera_id>\d+).json$', 'gk.views.get_camera'),
                       url(r'^vote-(?P<camera_id>\d+).json$', 'gk.views.vote'),
                       url(r'^addfav/(?P<camera_id>\d+)/$', 'gk.views.addfav'),
                       url(r'^rmfav/(?P<camera_id>\d+)/$', 'gk.views.rmfav'),
                       url(r'^favcams/', 'gk.views.favcams'),
                       #CP
                       url(r'^cp/', include('cp.urls')),
                       #news
                       url(r'^news/', include('news.urls')),
                       #Admin
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       #advertising test
                       url(r'^adver/', 'gk.views.adver'),
                       (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

                       #Copy
                       # url(r'^xindex/', 'gk.views.xindex', name='xindex'),
                       # url(r'^xabout/', 'gk.views.xabout', name='xabout'),
                       # url(r'^xads/', 'gk.views.xads', name='xads'),
                       # url(r'^xcontacts/', 'gk.views.xcontacts', name='xcontacts'),
)

news/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User
from gk.models import City


class Tag(models.Model):
    name = models.CharField(max_length=300, verbose_name=u'Метка')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u"Тег"
        verbose_name_plural = u"Теги"


class Categoryitem(models.Model):
    parent = models.ForeignKey('self', verbose_name=u'Категория родитель', blank=True, null=True)
    name = models.CharField(max_length=200, verbose_name=u'Название')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u"Категория"
        verbose_name_plural = u"Категории"


class News(models.Model):
    active = models.BooleanField(verbose_name=u'Опубликовано')
    owner = models.ForeignKey(User, verbose_name=u'Пользователь')
    title = models.CharField(max_length=500, verbose_name=u'Заголовок')
    text = models.TextField(verbose_name=u'Текст новости')
    tags = models.ManyToManyField(Tag, verbose_name=u'Теги')
    category = models.ManyToManyField(Categoryitem, verbose_name=u'Категория')
    date = models.DateTimeField(verbose_name=u'Дата публикации')
    autor = models.CharField(max_length=500, blank=True, null=True, verbose_name=u'Автор')
    origin = models.CharField(max_length=500, blank=True, null=True, verbose_name=u'Источник')
    photo_title = models.CharField(max_length=500, blank=True, null=True, verbose_name=u'Источник фото')
    media = models.CharField(max_length=4000, blank=True, null=True, verbose_name=u'Медиа контент')
    sweight = models.DecimalField(max_digits=3, decimal_places=2, default=0, verbose_name=u'Поимсковый вес')
    city = models.ForeignKey(City, verbose_name=u'Город', blank=True, null=True)


def __unicode__(self):
    return self.title


class Meta:
    verbose_name = u"Новость"
    verbose_name_plural = u"Новости"


class Comment(models.Model):
    news = models.ForeignKey(News, verbose_name=u'Новость')
    date = models.DateField(auto_now_add=True, verbose_name=u'Дата')
    parent = models.ForeignKey('self', verbose_name=u'Коментарий родитель', blank=True, null=True)
    owner = models.ForeignKey(User, verbose_name=u'Пользователь')
    text = models.TextField(verbose_name=u'Текст коментария')

news/views.py
# coding=utf-8
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import permission_required, login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from models import News, City, Categoryitem, Tag, Comment
from PIL import Image
import datetime


def handle_uploaded_file(f, name):
    destination = open('/tmp/' + name, 'wb+')
    for chunk in f.chunks():
        destination.write(chunk)
    destination.close()
    return name


@permission_required('news.add_news', login_url='/reg/')
def admin(request):
    c = Categoryitem.objects.select_related().filter(parent=None)
    t = Tag.objects.all()
    n = News.objects.all().order_by('-id')
    ct = City.objects.all()
    context = {'news': n,
               'tags': t,
               'citys': ct,
               'cats': c}
    return render(request, 'news/admin.html', context)


# @permission_required('news.add_news', login_url='/reg/')
# def xadmin(request):
#     c = Categoryitem.objects.select_related().filter(parent=None)
#     t = Tag.objects.all()
#     n = News.objects.all().order_by('-id')
#     ct = City.objects.all()
#     context = {'title': '| Администрирование новостей',
#                'news': n,
#                'tags': t,
#                'citys': ct,
#                'cats': c}
#     return render(request, 'news/xadmin.html', context)


# def index(request, page='1'):
#     if "cat" in request.COOKIES:
#         if request.COOKIES["cat"] == '0':
#             n = News.objects.all().order_by('-id')
#             cname = 'Подмосковья'
#         else:
#             n = News.objects.all().order_by('-id').filter(category__in=[request.COOKIES["cat"]])
#             cname = 'Электростали'
#     else:
#         n = News.objects.all().order_by('-id')
#         cname = 'Подмосковья'
#     c = Categoryitem.objects.select_related().filter(parent=None)
#     paginator = Paginator(n, 5)
#     try:
#         n = paginator.page(page)
#     except PageNotAnInteger:
#         n = paginator.page(1)
#     except EmptyPage:
#         n = paginator.page(paginator.num_pages)
#     context = {'title': ' Новости Подмосковья ',
#                'news': n,
#                'cats': c,
#                'cat': cname}
#     return render(request, 'news/index.html', context)


def index(request, page='1'):
    from_date = datetime.datetime.now() - datetime.timedelta(days=2)
    l2dn = News.objects.all().order_by('-date').filter(date__range=[from_date, datetime.datetime.now()])
    n = News.objects.all().order_by('-date')
    c = Categoryitem.objects.select_related().filter(parent=None)
    paginator = Paginator(n, 5)
    try:
        n = paginator.page(page)
    except PageNotAnInteger:
        n = paginator.page(1)
    except EmptyPage:
        n = paginator.page(paginator.num_pages)
    context = {'news': n,
               'cats': c,
               'last_news': l2dn}
    return render(request, 'news/index.html', context)


# def sp(request, id='1'):
#     if request.method == "POST":
#         text = request.POST['text']
#         user = User.objects.get(username=request.user)
#         nn = get_object_or_404(News, id=id)
#         nc = Comment()
#         nc.owner = user
#         nc.text = text
#         nc.news = nn
#         nc.save()
#         return redirect(request.path)
#     n = get_object_or_404(News, id=id)
#     c = Categoryitem.objects.select_related().filter(parent=None)
#     com = Comment.objects.select_related().filter(news=n, parent=None)
#     context = {'title': ' Новостная запись ',
#                'news': n,
#                'cats': c,
#                'comments': com}
#     return render(request, 'news/sp.html', context)


def sp(request, id='1'):
    if request.method == "POST":
        text = request.POST['text']
        user = User.objects.get(username=request.user)
        nn = get_object_or_404(News, id=id)
        nc = Comment()
        nc.owner = user
        nc.text = text
        nc.news = nn
        nc.save()
        return redirect(request.path)
    from_date = datetime.datetime.now() - datetime.timedelta(days=2)
    l2dn = News.objects.all().order_by('-date').filter(date__range=[from_date, datetime.datetime.now()])
    ln = News.objects.all()[:5]
    ct = City.objects.all()
    n = get_object_or_404(News, id=id)
    c = Categoryitem.objects.select_related().filter(parent=None)
    com = Comment.objects.select_related().filter(news=n, parent=None)
    context = {'news': n,
               'cats': c,
               'citys': ct,
               'comments': com,
               'lnews': ln,
               'last_news': l2dn}
    return render(request, 'news/sp.html', context)


@permission_required('news.add_news', login_url='/reg/')
def add_news(request):
    imgroot = '/var/pj/gk/st/news/'
    imgroot54x54 = '/var/pj/gk/st/news/54x54/'
    if request.method == "POST":
        title = request.POST['news_name']
        tags = request.POST['news_tags']
        active = request.POST['news_status']
        category = request.POST['news_category']
        sweight = request.POST['news_priority']
        date = request.POST['news_date']
        text = request.POST['news_content']
        n = News()
        if 'news_autor' in request.POST:
            n.autor = request.POST['news_autor']
        if 'news_photo_autor' in request.POST:
            n.photo_title = request.POST['news_photo_autor']
        if 'news_origin' in request.POST:
            n.origin = request.POST['news_origin']
        if 'news_city' in request.POST:
            n.city = request.POST['news_city']
        if 'news_media' in request.POST:
            n.media = request.POST['news_media']
        user = User.objects.get(username=request.user)
        n.owner = user
        n.title = title
        if active == 'on':
            active = True
        else:
            active = False
        n.active = active
        n.text = text
        n.sweight = sweight
        n.date = date
        n.save()
        tagsl = tags.split(',')
        tagsitems = []
        for item in tagsl:
            if len(item.strip()):
                tagsitems.append(Tag.objects.get_or_create(name=item.strip())[0].id)
        n.tags = tagsitems
        categoryl = category.split(',')
        categoryitems = []
        for item in categoryl:
            if len(item.strip()):
                categoryitems.append(item)
        n.category = categoryitems
        tmpfile = handle_uploaded_file(request.FILES['news_logo'], str(n.id) + request.FILES['news_logo'].name[-4:])
        img = Image.open('/tmp/' + tmpfile)
        img.save(imgroot + str(n.id) + '.png', 'PNG')
        img.thumbnail([54, 54], Image.ANTIALIAS)
        img.save(imgroot54x54 + str(n.id) + '.png', 'PNG')
        request.session['alert'] = 'Новость успешно добавлена'
        return redirect('/news/admin/')


@permission_required('news.change_news', login_url='/reg/')
def edit_news(request):
    if request.method == "POST":
        title = request.POST['edit_news_name']
        tags = request.POST['edit_news_tags']
        id = request.POST['edit_news_id']
        text = request.POST['edit_news_content']
        category = request.POST['edit_news_cat']
        n = News.objects.get(id=id)
        n.title = title
        n.text = text
        n.save()
        tagsl = tags.split(',')
        tagsitems = []
        for item in tagsl:
            tagsitems.append(Tag.objects.get_or_create(name=item.strip())[0].id)
        n.tags = tagsitems
        categoryl = category.split(',')
        categoryitems = []
        for item in categoryl:
            if len(item.strip()):
                categoryitems.append(item)
        n.category = categoryitems
        request.session['alert'] = 'Новость успешно отредактирована'
        return redirect('/news/sp/' + id)


@permission_required('news.add_categoryitem', login_url='/reg/')
def add_category(request):
    if request.method == "POST":
        name = request.POST['cat_name']
        parent = request.POST['parent_cat']
        c = Categoryitem()
        if parent != '0':
            pc = get_object_or_404(Categoryitem, id=parent)
            c.parent = pc
        c.name = name
        c.save()
        request.session['alert'] = 'Категория успешно добавлена'
        return redirect('/news/admin/')


def addcomment(request):
    if request.method == "POST":
        news = News.objects.get(id=request.POST['news'])
        text = request.POST['text']
        user = User.objects.get(username=request.user)
        c = Comment()
        c.news = news
        c.owner = user
        c.text = text
        if request.POST['pid'] != 'false':
            pid = request.POST['pid']
            c.parent = Comment.objects.get(id=pid)
        c.save()
        return HttpResponse(c.id)


@permission_required('news.delete_categoryitem', login_url='/reg/')
def remcat(request):
    if request.method == "POST":
        cats = request.POST['category']
        catsl = cats.split(',')
        for item in catsl:
            c = Categoryitem.objects.get(id=item)
            c.delete()
        request.session['alert'] = 'Категория(и) успешно удалены.'
        return redirect('/news/admin/')


@permission_required('news.delete_news', login_url='/reg/')
def remnews(request):
    if request.method == "POST":
        news = request.POST['news']
        newsl = news.split(',')
        for item in newsl:
            n = News.objects.get(id=item)
            n.delete()
        request.session['alert'] = 'Новость(и) успешно удалены.'
        return redirect('/news/admin/')


@permission_required('news.delete_tag', login_url='/reg/')
def remtags(request):
    if request.method == "POST":
        tags = request.POST['tags']
        tagsl = tags.split(',')
        for item in tagsl:
            t = Tag.objects.get(id=item)
            t.delete()

templates/news/index.html
{% extends "base" %}
{% load webdesign %}
{% block pagetitle %}Новости Подмосковья на портале «Город камер»{% endblock %}
{% block title %}Город камер | Новости Подмосковья | Проект «Безопасный город»{% endblock %}
{% block yaParams %}Новости Подмосковья{% endblock %}
{% block ogtitle %}Город камер | Новости Подмосковья | Проект «Безопасный город»{% endblock %}
{% block description %}Новости Подмосковья на портале Город камер. Проект программы «Безопасный город».{% endblock %}
{% block keywords %}новости подмосковья, новости подмосковья на городе камер, Подмосковье, Жуковский, Раменское, Балашиха, Павловский посад, Электросталь, Ногинск {% endblock %}
{% block toggleaside %}
<div class="header-actions pull-right">
    <a id="toggle-aside" class="btn btn-icon" role="button"><i class="icon ion-navicon-round"></i></a>
</div><!-- /header actions -->
{% endblock %}
<!-- Individual scripts for page -->
{% block scripts %}
<script src="/st/cp/bootstrap-paginator/bootstrap-paginator.js"></script>
<!-- VK -->
<script type="text/javascript" src="//vk.com/js/api/openapi.js?105"></script>
<script type="text/javascript">
    VK.init({apiId: 4163448, onlyWidgets: true});
</script>
<!--VK end-->
<script src="/st/cp/jquery-prettyPhoto/js/jquery.prettyPhoto.js"></script>
<script src="/st/cp/app/js/news.js"></script>

{% if request.path != '/news/' %}
<script>
    jQuery(document).ready(function () {
        var options = {
            currentPage: {{ news.number }},
            pageUrl: function(type, page, current){
                return "/news/page/"+page +"/";
            },
            onPageClicked: function(e,originalEvent,type,page){
                e.stopImmediatePropagation();
            },
            bootstrapMajorVersion: 3,
            numberOfPages:3,
            totalPages: {{ news.paginator.num_pages }}
        }
        jQuery('#news_paginator').bootstrapPaginator(options);
    })
</script>
{% endif %}
{% endblock %}
{% block content %}
            <!-- app body -->
            <div class="app-body">
                <!-- app content here -->
                <div class="magic-layout"><!-- /magic layout -->
                    {% for item in news %}
                    <div class="panel panel-default magic-element width-full">
                        {% if item.city %}
                        <div class="panel-heading">
                            <div class="panel-icon"><img src="/st/img/citylogo/{{ item.city.id }}.png" height="30px"></div>
                            <h3 class="panel-title">{{ item.city }}</h3>
                        </div>
                        {% endif %}
                        {% if forloop.first %}
                        <div class="kits-media col-md-3" style="padding: 10px">
                            <div class="post-image">
                                <a href="/st/news/{{ item.id }}.png" data-rel="prettyPhoto" alt="{{ item.title }}" title="{{ item.title }}">
                                    <span class="img-hover"></span>
                                    <span class="fullscreen"><i class="icon ion-search"></i></span>
                                    <img itemprop="image" src="/st/news/{{ item.id }}.png" alt="{{ item.title }}" title="{{ item.title }}" width="100%" itemprop="contentUrl">
                                    <meta itemprop="description" content="{{ item.title }}">
                                    <meta itemprop="name" content="{{ item.title }}">
                                </a>
                            </div>
                        </div><!-- /kits-media -->
                        {% endif %}
                        <div class="panel-body">
                            <div class="todo-list">
                                <div class="label label-success">{{ item.date|date:"d-m-Y" }}</div>
                                <h4 class="todo-text">{{ item.title }}</h4>
                            </div>
                            {% autoescape off %}
                            {{ item.text|striptags|truncatewords:36 }}
                            {% endautoescape %}
                        </div><!-- /panel-body -->
                        <div class="panel-footer">
                            <a href="/news/sp/{{ item.id }}/" class="btn btn-ion btn-primary pull-right">Читать далее</a>
                            <a href="#" class="btn btn-ion btn-primary" disabled="disabled"><i class="icon ion-social-facebook"></i></a>
                            <a href="#" class="btn btn-ion btn-info" disabled="disabled"><i class="icon ion-social-twitter"></i></a>
                            <a href="#" class="btn btn-ion btn-danger" disabled="disabled"><i class="icon ion-social-googleplus"></i></a>
                        </div><!-- /panel-footer -->
                    </div>
                    {% endfor %}

                    {% if request.path != '/news/' %}
                    <div class="panel panel-default magic-element width-full text-center">
                        <ul id="news_paginator"></ul>
                    </div>
                    {% else %}
                    <div class="panel panel-default magic-element width-full">
                        <a href="/news/page/1/" class="btn btn-primary btn-lg btn-block">Показать все новости</a>
                    </div>
                    {% endif %}
                </div><!-- /magic layout -->
            </div><!-- /app body -->
        </div><!-- /content app -->
    </section><!-- /content main -->
    <section id="content-aside" class="content-aside">
        <!-- your module content -->
        <div class="content-module fixed-header">
            <!-- module header -->
            <div class="module-header">
                <h3 class="module-title">
                    Последние новости
                </h3>
            </div><!-- /module header -->
            <!-- module body -->
            <div class="module-body">
                <!-- app module here -->
                <div class="panel panel-default magic-element" style="margin:10px">
                    <div class="panel-body category">
                        <h3 class="title">Категории</h3>
                        <form action="/news/filter/" method="post" style="margin-top: 15px">
                            {% csrf_token %}
                            <input type="hidden" name="category">
                            {% load recurse %}
                            {% recurse cat.categoryitem_set.all with cats as cat %}
                            <ul class="tree" style="padding:0px 0px 10px 0px;list-style-type:none;{% if level %}margin-left: 38px;display:none;{% endif %}">
                                {% loop %}
                                <li style="content: normal">
                                    {% if childexist %}<i class="icon ion-plus tree-toggle tree-close" style="cursor:pointer;margin-right:5px"></i>{% endif %}
                                    <input type="checkbox" value="{{ cat.id }}" style="margin-right:5px"><a class="tree-item" href="#">{{ cat.name }}</a>
                                    {% child %}
                                </li>
                                {% endloop %}
                            </ul>
                            {% endrecurse %}
                            <button type="submit" class="btn btn-color">Фильтр</button>
                        </form>
                    </div>
                </div>
            </div><!-- /module body -->
        </div><!-- /content module -->
    </section><!-- /content asside -->
{% endblock %}